Fix i2c parameter documentation
adafruit/Adafruit_CircuitPython_ServoKit pull request #49
Opened 2023-05-22 18:35 UTC by spovlot

2023-05-22 22:34 UTC, tekktrik commented
Just wanted to say that you can ignore the warning about the exceptions, I'll fix that this week.  The "line too long" one should get fixed however.

2023-05-30 13:20 UTC, tekktrik requested changes

2023-05-30 13:20 UTC, tekktrik commented on adafruit_servokit.py
> +    :param ~I2C i2c: The I2C bus to use. If not provided, the default I2C ``board.I2C()`` will be used.
Looks like this just needs to be split into two lines like some of the other docstring params here.

2023-05-30 13:45 UTC, tekktrik commented
Looks like running `pre-commit` (specifically `black`) one last time should fix it now!

2023-07-30 18:57 UTC, FoamyGuy approved these changes
Looks good. Thank you @spovlot!

2023-07-30 18:57 UTC, merged